### ISSUE TITLE
[Feature] Add functionality to do validation

### ISSUE THREAD

**Issue by AyushBherwani1998** [maheshmnj/searchfield#3]
## Description

As of now, if user don't select any value from the given suggestions, it's accepted as a valid value. For instance, if the drop down is about states in India, and if enter xyz, it would consider a valid value for the state. 

The idea is to add a `validation` property and use `TextFormField` instead of `TextField`. After addition if developer wraps `SearchField` with `Form` and passes a validator, it will help to validate the input.

**Comment by maheshmnj** [comment]
@AyushBherwani1998  Its added now in this commit https://github.com/maheshmnj/searchfield/commit/7c9db449290bf4d3fd3e78a4cc46cc8b5ff45e1f

but I am confused about versioning the package because this feature is now only available under null safety how do we add this feature to the projects without null safety do we need to separately make another non null safe commit?

**Comment by AyushBherwani1998** [comment]
Oh yeah, this could be tricky. We should have done this earlier I suppose :(

Sorry for not suggesting earlier, but we could keep two branch, master - for stable version and a null-safe branch - for release. As soon as null safe comes in stable, you can merge null-safe branch into master

**Comment by maheshmnj** [comment]
okay no worries thanks for the suggestion I will do that

**Comment by maheshmnj** [comment]
And I assume the requested feature is addressed so I am closing this issue. Feel free to create new feature request or report a issue :)

**Comment by AyushBherwani1998** [comment]
LGTM, thanks :D
